# coding: utf-8

"""
    COVID-19 Local API

    API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import covid_local
from covid_local.api.default_api import DefaultApi  # noqa: E501
from covid_local.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = covid_local.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all(self):
        """Test case for get_all

        Get all items for a place  # noqa: E501
        """
        pass

    def test_get_health_departments(self):
        """Test case for get_health_departments

        Get responsible health departments for a place  # noqa: E501
        """
        pass

    def test_get_hotlines(self):
        """Test case for get_hotlines

        Get hotlines for a place  # noqa: E501
        """
        pass

    def test_get_test_sites(self):
        """Test case for get_test_sites

        Get nearby test sites for a place (sorted by distance to place)  # noqa: E501
        """
        pass

    def test_get_websites(self):
        """Test case for get_websites

        Get websites for a place  # noqa: E501
        """
        pass

    def test_search_places(self):
        """Test case for search_places

        Search for places via free-form query  # noqa: E501
        """
        pass

    def test_test(self):
        """Test case for test

        Shows all entries for Berlin Mitte (redirects to /all endpoint)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
