# coding: utf-8

"""
    COVID-19 Local API

    API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "covid-local-py"
VERSION = "0.1.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="COVID-19 Local API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="https://github.com/cotect/covid-local-py",
    keywords=["OpenAPI", "OpenAPI-Generator", "COVID-19 Local API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)  # noqa: E501
    """
)
