# coding: utf-8

# flake8: noqa
"""
    COVID-19 Local API

    API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from covid_local.models.http_validation_error import HTTPValidationError
from covid_local.models.health_department import HealthDepartment
from covid_local.models.hotline import Hotline
from covid_local.models.place import Place
from covid_local.models.results_list import ResultsList
from covid_local.models.test_site import TestSite
from covid_local.models.validation_error import ValidationError
from covid_local.models.website import Website
