# coding: utf-8

"""
    COVID-19 Local API

    API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from covid_local.configuration import Configuration


class HealthDepartment(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'country_code': 'str',
        'place': 'str',
        'geonames_id': 'int',
        'name': 'str',
        'department': 'str',
        'street': 'str',
        'zip_code': 'int',
        'city': 'str',
        'address_supplement': 'str',
        'phone': 'str',
        'fax': 'str',
        'email': 'str',
        'website': 'str',
        'sources': 'str'
    }

    attribute_map = {
        'country_code': 'country_code',
        'place': 'place',
        'geonames_id': 'geonames_id',
        'name': 'name',
        'department': 'department',
        'street': 'street',
        'zip_code': 'zip_code',
        'city': 'city',
        'address_supplement': 'address_supplement',
        'phone': 'phone',
        'fax': 'fax',
        'email': 'email',
        'website': 'website',
        'sources': 'sources'
    }

    def __init__(self, country_code=None, place=None, geonames_id=None, name=None, department=None, street=None, zip_code=None, city=None, address_supplement=None, phone=None, fax=None, email=None, website=None, sources=None, local_vars_configuration=None):  # noqa: E501
        """HealthDepartment - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._country_code = None
        self._place = None
        self._geonames_id = None
        self._name = None
        self._department = None
        self._street = None
        self._zip_code = None
        self._city = None
        self._address_supplement = None
        self._phone = None
        self._fax = None
        self._email = None
        self._website = None
        self._sources = None
        self.discriminator = None

        if country_code is not None:
            self.country_code = country_code
        if place is not None:
            self.place = place
        if geonames_id is not None:
            self.geonames_id = geonames_id
        if name is not None:
            self.name = name
        if department is not None:
            self.department = department
        if street is not None:
            self.street = street
        if zip_code is not None:
            self.zip_code = zip_code
        if city is not None:
            self.city = city
        if address_supplement is not None:
            self.address_supplement = address_supplement
        if phone is not None:
            self.phone = phone
        if fax is not None:
            self.fax = fax
        if email is not None:
            self.email = email
        if website is not None:
            self.website = website
        if sources is not None:
            self.sources = sources

    @property
    def country_code(self):
        """Gets the country_code of this HealthDepartment.  # noqa: E501


        :return: The country_code of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._country_code

    @country_code.setter
    def country_code(self, country_code):
        """Sets the country_code of this HealthDepartment.


        :param country_code: The country_code of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._country_code = country_code

    @property
    def place(self):
        """Gets the place of this HealthDepartment.  # noqa: E501


        :return: The place of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._place

    @place.setter
    def place(self, place):
        """Sets the place of this HealthDepartment.


        :param place: The place of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._place = place

    @property
    def geonames_id(self):
        """Gets the geonames_id of this HealthDepartment.  # noqa: E501


        :return: The geonames_id of this HealthDepartment.  # noqa: E501
        :rtype: int
        """
        return self._geonames_id

    @geonames_id.setter
    def geonames_id(self, geonames_id):
        """Sets the geonames_id of this HealthDepartment.


        :param geonames_id: The geonames_id of this HealthDepartment.  # noqa: E501
        :type: int
        """

        self._geonames_id = geonames_id

    @property
    def name(self):
        """Gets the name of this HealthDepartment.  # noqa: E501


        :return: The name of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HealthDepartment.


        :param name: The name of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def department(self):
        """Gets the department of this HealthDepartment.  # noqa: E501


        :return: The department of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._department

    @department.setter
    def department(self, department):
        """Sets the department of this HealthDepartment.


        :param department: The department of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._department = department

    @property
    def street(self):
        """Gets the street of this HealthDepartment.  # noqa: E501


        :return: The street of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._street

    @street.setter
    def street(self, street):
        """Sets the street of this HealthDepartment.


        :param street: The street of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._street = street

    @property
    def zip_code(self):
        """Gets the zip_code of this HealthDepartment.  # noqa: E501


        :return: The zip_code of this HealthDepartment.  # noqa: E501
        :rtype: int
        """
        return self._zip_code

    @zip_code.setter
    def zip_code(self, zip_code):
        """Sets the zip_code of this HealthDepartment.


        :param zip_code: The zip_code of this HealthDepartment.  # noqa: E501
        :type: int
        """

        self._zip_code = zip_code

    @property
    def city(self):
        """Gets the city of this HealthDepartment.  # noqa: E501


        :return: The city of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this HealthDepartment.


        :param city: The city of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def address_supplement(self):
        """Gets the address_supplement of this HealthDepartment.  # noqa: E501


        :return: The address_supplement of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._address_supplement

    @address_supplement.setter
    def address_supplement(self, address_supplement):
        """Sets the address_supplement of this HealthDepartment.


        :param address_supplement: The address_supplement of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._address_supplement = address_supplement

    @property
    def phone(self):
        """Gets the phone of this HealthDepartment.  # noqa: E501


        :return: The phone of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this HealthDepartment.


        :param phone: The phone of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def fax(self):
        """Gets the fax of this HealthDepartment.  # noqa: E501


        :return: The fax of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._fax

    @fax.setter
    def fax(self, fax):
        """Sets the fax of this HealthDepartment.


        :param fax: The fax of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._fax = fax

    @property
    def email(self):
        """Gets the email of this HealthDepartment.  # noqa: E501


        :return: The email of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this HealthDepartment.


        :param email: The email of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def website(self):
        """Gets the website of this HealthDepartment.  # noqa: E501


        :return: The website of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._website

    @website.setter
    def website(self, website):
        """Sets the website of this HealthDepartment.


        :param website: The website of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._website = website

    @property
    def sources(self):
        """Gets the sources of this HealthDepartment.  # noqa: E501


        :return: The sources of this HealthDepartment.  # noqa: E501
        :rtype: str
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this HealthDepartment.


        :param sources: The sources of this HealthDepartment.  # noqa: E501
        :type: str
        """

        self._sources = sources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HealthDepartment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HealthDepartment):
            return True

        return self.to_dict() != other.to_dict()
