# coding: utf-8

# flake8: noqa

"""
    COVID-19 Local API

    API to get local help information about COVID-19 (hotlines, websites, test sites, health departments)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.health_department import HealthDepartment
from openapi_client.models.hotline import Hotline
from openapi_client.models.place import Place
from openapi_client.models.results_list import ResultsList
from openapi_client.models.test_site import TestSite
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.website import Website

